name: minecraft-nsg
title: Minecraft-NSG
version: '10.0'

summary: A simple installer for Minecraft - Java Edition
description: | 
  A simple installer for Minecraft - Java Edition.
license: MIT

assumes:
  - command-chain
  
base: core20
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64

apps:
  minecraft-nsg:
    extensions:
      - gnome-3-38
    command: launch
    command-chain: 
      - bin/homeishome-launch    
    plugs:
      - network
      - opengl
      - audio-playback
      - browser-support
    environment:
      PYTHONPATH: $SNAP_DESKTOP_RUNTIME/usr/lib/python3.8/site-packages
      JAVA_HOME: $SNAP/usr/lib/jvm/java-16-openjdk-amd64/
      __NV_PRIME_RENDER_OFFLOAD: 1
      __GLX_VENDOR_LIBRARY_NAME: nvidia      

parts:
  launcher:
    plugin: dump
    source: scripts
    
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch        

  game:
    plugin: nil
    build-packages:
      - openjdk-16-jre-headless        
      - ca-certificates-java
      - ca-certificates      
    stage-packages:
      - libglu1-mesa
      - libswt-gtk-4-java
      - python3-requests
      - openjdk-16-jre-headless
      - libxss1
      - libgconf-2-4
      - libcurl4
      - x11-xserver-utils

  cleanup:
    after: 
      - game
      - launcher
    plugin: nil
    build-snaps: 
      - core20
      - gnome-3-38-2004
    override-prime: |
      set -eux
      for snap in "core20" "gnome-3-38-2004"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
