#!/bin/bash

export LIBGL_DRIVERS_PATH=$SNAP/usr/lib/x86_64-linux-gnu/dri
export JAVA_HOME=$SNAP_USER_DATA/jdk1.8.0_101/

set -e
$SNAP/download

$JAVA_HOME/bin/java \
	-Duser.home=$HOME/appdata \
	-jar $SNAP_USER_DATA/Minecraft.jar
