#!/bin/bash

export LIBGL_DRIVERS_PATH=$SNAP/usr/lib/x86_64-linux-gnu/dri
export JAVA_HOME=$SNAP/usr/lib/jvm/java-8-openjdk-amd64/

set -e
(
	cd $SNAP_USER_DATA
	$SNAP/download-launcher.py
)

java \
	-Duser.home=$HOME/appdata \
	-jar $SNAP_USER_DATA/Minecraft.jar
