#!/bin/bash

export LIBGL_DRIVERS_PATH=$SNAP/usr/lib/x86_64-linux-gnu/dri
export JAVA_HOME=$SNAP_USER_DATA/jdk1.8.0_151/

set -e
(
	cd $SNAP_USER_DATA
	if [ ! -e $JAVA_HOME ]; then
		$SNAP/download-java.py
		tar xf jdk-*-linux-x64.tar.gz
		rm jdk-*-linux-x64.tar.gz
	fi
	$SNAP/download-launcher.py
)


$JAVA_HOME/bin/java \
	-Duser.home=$HOME/appdata \
	-jar $SNAP_USER_DATA/Minecraft.jar
