#!/bin/bash

yad \
	--title="Accept License" \
	--text="Do you agree to the license at:
http://www.oracle.com/technetwork/java/javase/terms/license/index.html

If you agree, Oracle JDK will be downloaded from oracle[1] and unpacked to your computer.

[1]: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html"

if [ $? == 0 ]; then
	exit 0
else
	yad \
		--title="Setup aborted" \
		--button=gtk-ok \
		--text="Setup was aborted, you need to accept the \nOracle Binary Code License to use Java to run Minecraft."
	exit 1
fi
